spring:
  application:
    name: user-service
  config:
    import: "optional:configserver:http://localhost:8089"
  datasource:
    url: jdbc:mysql://localhost:3306/highwayTicket
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
server:
  port: 8082